version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9
  cxflow: checkmarx-ts/cxflow@1.0.4

  jobs:
    cx-scan:
      executor: cxflow/default
      steps:
        - checkout
        - cxflow/scan:
            team: "\\CxServer\\SP\\Checkmarx\\JayN"
            preset: "Checkmarx Express"
            report-file: checkmarx.json
        - store_artifacts:
            path: checkmarx.json

  workflows:
    version: 2
    sast-scan:
      jobs:
        - cx-scan:
            filters:
              branches:
                only: Feature/combine-all-scanners-configuration


#      - orb-tools/lint
#      - orb-tools/pack:
#          source-dir: src
#          destination-orb-path: orb.yml
#          workspace-path: orb.yml
#          artifact-path: orb.yml
#          requires: [orb-tools/lint]
#      - orb-tools/publish-dev:
#          orb-name: checkmarx-ts/cxflow
#          requires: [orb-tools/pack]
#      - orb-tools/publish:
#          orb-ref: checkmarx-ts/cxflow@1.0.4
#          attach-workspace: true
#          requires: [orb-tools/publish-dev]
#          filters:
#            branches:
#              only: Feature/combine-all-scanners-configuration
