version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9
  cxflow: jay-test/cxflow-scanners-orb@dev:alpha

workflows:
  version: 2
  sast-scan:
    jobs:
      - cxflow/scan:
          project: CxProject
          team: "\\CxServer\\SP\\Checkmarx\\JayN"
          preset: "Checkmarx Express"
          report-file: vulns.json
          scanners: ast
          sca-appUrl: https://sca.scacheckmarx.com
          sca-apiUrl: https://api.scacheckmarx.com
          sca-accessControlUrl: https://platform.checkmarx.net
          ast-apiUrl: http://ec2-3-249-214-110.eu-west-1.compute.amazonaws.com



#      - orb-tools/lint
#      - orb-tools/pack:
#          source-dir: src
#          destination-orb-path: orb.yml
#          workspace-path: orb.yml
#          artifact-path: orb.yml
#          requires: [orb-tools/lint]
#      - orb-tools/publish-dev:
#          orb-name: checkmarx-ts/cxflow
#          requires: [orb-tools/pack]
#      - orb-tools/publish:
#          orb-ref: checkmarx-ts/cxflow@1.0.4
#          attach-workspace: true
#          requires: [orb-tools/publish-dev]
#          filters:
#            branches:
#              only: Feature/combine-all-scanners-configuration
