version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9
  cxflow: jay-test/cxflow-scanners-orb@dev:alpha

workflows:
  version: 2
  sast-scan:
    jobs:
      - cxflow/files
      - cxflow/scan:
          project: CxProject
          team: "\\CxServer\\SP\\Checkmarx\\JayN"
          preset: "Checkmarx Express"
          report-file: vulns.json
          enabled-vulnerability-scanners: sca
          sca-username: cxflow
          sca-tenant: SCA-Champions
          sca-password: Cxflow@123

#      - orb-tools/lint
#      - orb-tools/pack:
#          source-dir: src
#          destination-orb-path: orb.yml
#          workspace-path: orb.yml
#          artifact-path: orb.yml
#          requires: [orb-tools/lint]
#      - orb-tools/publish-dev:
#          orb-name: checkmarx-ts/cxflow
#          requires: [orb-tools/pack]
#      - orb-tools/publish:
#          orb-ref: checkmarx-ts/cxflow@1.0.4
#          attach-workspace: true
#          requires: [orb-tools/publish-dev]
#          filters:
#            branches:
#              only: Feature/combine-all-scanners-configuration
